### ISSUE TITLE
Try to do Image of particles in 3D using #threejs - Tutorial n°4 but Fragment error

### ISSUE THREAD

**Issue by ninesixfiveseven** [Robpayot/vite-threejs-template#1]
Hi, I'm beginner for 3js! I try to do follow tutorial and I have a problem main.fragment. I use shader from https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib/points.glsl.js 

It still error Uncaught (in promise) Error: Can not resolve #include <alphahash_pars_fragment> and another include, my three version is     "three": "^0.149.0" .

Thank you!

**Comment by Robpayot** [comment]
Hi there, thanks for pointing it out! That's probably because these` #includes` has been added after the Threejs version you're using (0.149). 

Either try to install the latest version of threejs and use this shader, Or keep your 0.149 Threejs version and remove these ` #includes` as I'm pretty sure you don't need them for this exercice.

Let me know if that worked for you!

**Comment by ninesixfiveseven** [comment]
That worked, thank you!
